### ISSUE TITLE
d-linter.ini ignored?

### ISSUE THREAD

**Issue by trikko** [Pure-D/atomize-d#30]
I try to configure atom + atomize-d with dcd, dscanner, atom-build and linter.

On d-linter.ini (generated option found on ctrl+shift+p menu and placed on project's root) I commented this line:
`;undocumented_declaration_check="true"`

But it still keeps reporting me that some functions are not documented. What's wrong?

**Comment by Vild** [comment]
You need to set it to false and not uncomment it.
The default value for that variable is true.

**Comment by trikko** [comment]
Interesting. I was used to add only overrides on config files. It would be clear (for me) if config file was all commented out.

**Comment by Vild** [comment]
This config file is generated by dscanner and contains its own default settings.

**Comment by trikko** [comment]
Of course, it was my misunderstanding of default :)
