### ISSUE TITLE
Setting "self" as a reference to "this"

### ISSUE THREAD

**Issue by MggMuggins** [Pure-D/atomize-d#33]
As I'm reading through the source, most methods of both major classes are setting ```self = this``` at some point. Is there any reason for this? It seems to me like it would work fine if you just pass this instead of self wherever self is used.

**Comment by WebFreak001** [comment]
the `this` in javascript doesn't refer to the class object that called it, but to the object before the dot before the function name in any function call, so in callbacks this will be not what we want and we use self = this in a scope where this is valid to make self a valid object. In typescript you can also create callbacks using `() => {}` which will automatically do the self = this thing (with a variable named this_). The workspace-d branch uses typescript so self shouldn't be used there anymore

**Comment by MggMuggins** [comment]
So those are safe to remove?

**Comment by WebFreak001** [comment]
only if you use () => {} and not function() {} and typescript
